# Generated by Django 4.1 on 2022-08-18 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('shipfee', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerlink', models.CharField(blank=True, max_length=500, null=True)),
                ('sellername', models.CharField(blank=True, max_length=500, null=True)),
                ('itemlocation', models.CharField(blank=True, max_length=500, null=True)),
                ('feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('sold', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ebay.product')),
            ],
        ),
    ]
